module.exports.AppBanner = require('./appBanner');
module.exports.Batch = require('./batch');
module.exports.Event = require('./event');
module.exports.AppliedEvent = require('./appliedEvent');
module.exports.AppUpdate = require('./appUpdate');
module.exports.User = require('./users');
module.exports.CareerObjective = require('./careerObjective');
module.exports.City = require('./cities');
module.exports.Candidate = require('./candidate');
module.exports.CandidateProfile = require('./candidateProfile');
module.exports.CandidateDoc=require('./candidatedoc')
module.exports.CandidateRegister=require('./candidateRegsiterModel');
module.exports.CandidateCareer = require('./candidateCareer');
module.exports.CandidateQualification = require('./candidateQualification');
module.exports.CandidateProject = require('./candidateProject');
module.exports.CandidateReference = require('./candidateReference');
module.exports.CorporateRegister=require('./corporateRegisterModel');
module.exports.Country = require('./countries');
module.exports.College = require('./college');
module.exports.CollegeDocuments = require('./collegeDocuments');
module.exports.CollegeTodo = require('./collegeTodo');
module.exports.CollegeSms = require('./collegeSms');
module.exports.CollegeRepresentative = require('./collegeRepresentative');
module.exports.Company = require('./company');
module.exports.CompanyExecutive = require('./companyExecutive');
module.exports.CoverLetter = require('./coverLetter');
module.exports.JobCategory = require('./jobCategory');
module.exports.JobSubCategory = require('./jobSubCategory');
module.exports.Qualification = require('./qualification');
module.exports.MockInterview = require('./mockInterview');
module.exports.MockQuestion = require('./mockQuestion');
module.exports.State = require('./states');
module.exports.Industry = require('./industry');
module.exports.Skill = require('./skills');
module.exports.SkillTest = require('./skillTest');
module.exports.SkillTestQuestion = require('./skillTestQuestion');
module.exports.SubIndustry = require('./subIndustry');
module.exports.SubQualification = require('./subQualification');
module.exports.TestCategory = require('./testCategory');
module.exports.Vacancy = require('./vacancy');
module.exports.VacancyType = require('./vacancyType');
module.exports.University = require('./university');
module.exports.Import = require("./import");
module.exports.HiringStatus = require('./hiringstatus');
module.exports.coinsOffers = require('./coinsOffers')
module.exports.PaymentDetails = require('./paymentDetails')
module.exports.CoinsAlgo = require('./coinsAlgo')
module.exports.AppliedJobs = require('./appliedJobs')
module.exports.template = require('./templates')
module.exports.Consumption = require('./consumption')
module.exports.SmsHistory = require('./smsHistory')
module.exports.CandidateCashBack = require('./candidateCashback')
module.exports.CashBackLogic = require('./cashBackLogic')
module.exports.CashBackRequest = require('./cashbackRequest')
module.exports.CandidateImport = require('./candidateImports')
module.exports.KycDocument = require('./kycDocument')
module.exports.Vouchers=require('./vouchers');
module.exports.VoucherUses=require('./voucherUses');
module.exports.Notification = require('./notification');
module.exports.Referral = require('./referral')
module.exports.VideoData=require('./videoData');
module.exports.Contact=require('./contact')
module.exports.LoanEnquiry = require('./loanEnquiry')
module.exports.Review = require('./reviews');
module.exports.Courses=require('./courses');
module.exports.Post=require('./post');
module.exports.CourseSectors=require('./courseSectors');
module.exports.AppliedCourses = require("./appliedCourses");
module.exports.FAQ = require("./chatfaqs");
module.exports.Center = require("./center");
module.exports.QualificationCourse = require("./qualificationCourse");
module.exports.EducationBoard = require("./educationBoard");
module.exports.Universities = require("./universities");
module.exports.StudentRegistration = require("./studentRegistration");
module.exports.AccessUser = require("./AccessUserSchema");
module.exports.Vertical = require("./verticals");
module.exports.Project = require("./Project");
module.exports.centerSchema = require("./center");
module.exports.Roles = require("./roleManagement");
module.exports.UserActivityLog = require("./userActivityLog");
module.exports.Status = require("./status");
module.exports.StatusB2b = require("./statusB2b");
module.exports.RewardStatus = require("./RewardStatus");
module.exports.ApprovalRequest = require("./approval");
module.exports.LeadAssignmentRule = require("./leadAssignmentRule");
module.exports.EventType = require("./eventType");
module.exports.QuestionAnswer = require("./questionAnswer");
module.exports.CandidateVisitCalender = require("./candidateVisitCalender");
module.exports.AttendanceTracking = require("./attendanceTracking");
module.exports.StatusLogs = require("./statusLogs");
module.exports.B2cFollowup = require("./b2cFollowup");
module.exports.DripMarketingRule = require("./dripMarkettingRule");
module.exports.ReEnquire = require("./reEnquire");
// module.exports.Manager = required("");
module.exports.Traine = require("./trainer")

module.exports.WhatsAppTemplate = require("./wATemplate");
module.exports.WhatsAppMessage = require("./whatsappMessage");
module.exports.ChatHistory = require("./chatHistory");


module.exports.TrainerTimeTable = require("./trainerTimeTable");
module.exports.Curriculum = require("./curriculum");
module.exports.DailyDiary = require("./dailydiary");
module.exports.AssignmentQuestions = require("./questionBank");
module.exports.AssignmentSubmission = require("./assignmentSubmission");
//b2b models
module.exports.TypeOfB2B = require("./b2b/typeOfB2B");
module.exports.LeadCategory = require("./b2b/leadCategory");
module.exports.FollowUp = require("./b2b/followUp");
module.exports.Lead = require("./b2b/lead");
module.exports.Source = require("./source");
module.exports.PlacementStatus = require("./PlacementStatus");
module.exports.Placement = require("./Placement");
module.exports.JobOffer = require("./jobOffer");
module.exports.UploadCandidates = require("./uploadCandidates");
module.exports.RewardClaim = require("./RewardClaim");